### ISSUE TITLE
Head is broken? 

### ISSUE THREAD

**Issue by ghost** [Pinoccio/firmware-pinoccio#11]
I just checked out this project, ran update.sh and pointed my Adruino IDE sketchbook directory to the root of this project folder. 

SerialFlash, ClearScoutScript ran successfully.  

Compiled and uploaded Bootstrap and this shows up in the console:

``` 
˘˛EEPROM checksum incorrect
Hello from Pinoccio!
 (Shell based on Bitlash v2.0 (c) 2014 Bill Roy)
 Custom Sketch (rev unknown)
 17718 bytes free
 Lead Scout ready
> unexpected number
```

When I type `wifi.config` I get this failure message:

```
wifi.config("myWifi", "Redacted")
> unexpected number
```

Went on hq.pinocc.io and tried adding a new troop, prompt stuck at "Finding your Lead Scout..."

Something is definitely broken. Can someone confirm with me?

**Comment by jingman** [comment]
I just ran `update.sh`, compiles and uploaded Bootstrap, and things are working fine. Going to try it on a Lead Scout and will update here.

**Comment by ghost** [comment]
@jingman what hardware version do you have?

**Comment by jingman** [comment]
Scout v1.0, WiFi Backpack v1.1 (although the backpack is labelled as v1.0, I don't think that's right, waiting for confirmation). You?

I'm assuming you've made sure that all the other libraries are updating completely when you run `update.sh`?

**Comment by jingman** [comment]
Oh, and, have you checked your startup functions? The fact that you get `unexpected number` on boot makes me think that something is trying to run immediately, that might not have the proper syntax or something. You can see startup functions by running `ls` in the console.

**Comment by ghost** [comment]
@jingman 

Ah! I forgot that startup functions are saved in the EEPROM. `rm *` fixed it. Thanks!

**Comment by jingman** [comment]
Woo!
