### ISSUE TITLE
Can't bootstrap a scout using Arduino IDE v.1.6.7

### ISSUE THREAD

**Issue by cylinderStudio** [Pinoccio/firmware-pinoccio#13]
I think I loaded the /hardware and /libraries folders correctly, and the correct board and port show up. I don't know what all the warnings are about, but the library it can't seem to find is in libraries/lwm/src/lwm/sys 

```
WARNING: Category '' in library GainspanS2W is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library Atmel Lightweight Mesh framework is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library Pinoccio is not valid. Setting to 'Uncategorized'
Warning: platform.txt from core 'Pinoccio AVR boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
Warning: platform.txt from core 'Pinoccio AVR boards' contains deprecated recipe.c.combine.pattern="{compiler.path}{compiler.c.elf.cmd}" {compiler.c.elf.flags} -mmcu={build.mcu} -o "{build.path}/{build.project_name}.elf" {object_files} "{build.path}/{archive_file}" "-L{build.path}" -lm, automatically converted to recipe.c.combine.pattern="{compiler.path}{compiler.c.elf.cmd}" {compiler.c.elf.flags} -mmcu={build.mcu} -o "{build.path}/{build.project_name}.elf" {object_files} "{archive_file_path}" "-L{build.path}" -lm. Consider upgrading this core.
In file included from /Users/cylinder/Documents/Arduino/libraries/pinoccio/src/Scout.h:12:0,
                 from /Users/cylinder/Documents/Arduino/libraries/pinoccio/examples/Bootstrap/Bootstrap.ino:11:
/Users/cylinder/Documents/Arduino/libraries/pinoccio/src/Pinoccio.h:21:31: fatal error: lwm/sys/sysConfig.h: No such file or directory
 #include "lwm/sys/sysConfig.h"
```

**Comment by cylinderStudio** [comment]
It appears to be a problem related to the current version of Arduino. When I revert to v1.6.4, it compiles fine and issues no warnings.

I suppose it could be related to the platform.txt file, similar to the issue this poster was facing:
http://www.toddklindt.com/blog/Lists/Posts/Post.aspx?ID=613

**Comment by matthijskooijman** [comment]
Could you enable verbose compilation in the preferences and post the full log?

**Comment by cylinderStudio** [comment]
Sure thing. Log attached.
[compile_log.txt](https://github.com/Pinoccio/firmware-pinoccio/files/101168/compile_log.txt)

**Comment by matthijskooijman** [comment]
Thanks for reporting. This should be fixed in library-pinoccio now. Could you confirm?

**Comment by cylinderStudio** [comment]
Sure thing. Where should I pull from to make sure I have your new commit?

**Comment by cylinderStudio** [comment]
Yep, that appears to have fixed it. Pulled from library-pinoccio, replaced that lib in the firmware and rebooted and it compiled fine. Thanks for jumping on this.

**Comment by matthijskooijman** [comment]
Cool!

**Comment by ghost** [comment]
Ehi

I have a similar issue related to the pinoccio library 

check it out here ---> https://github.com/Pinoccio/library-pinoccio/issues/239 

Wondering if anyone knows about those cloud keys 

cheers
