### ISSUE TITLE
Add `hqprint` function or equivalent feature (send strings to Carlo)

### ISSUE THREAD

**Issue by jingman** [Pinoccio/firmware-pinoccio#4]
Right now, serial prints are only sent to carlo if they are the result of a command. If you have a print inside a function that's running in the background, it goes to the serial port, but not HQ.

There should "print-like" function that prints something to HQ (in fact, it's not necessarily a requirement that the output goes to serial at all).

**Comment by quartzjer** [comment]
For now, that is easily accomplished with mesh.announce(0,"foo","bar"), that generates an announcement that gets sent to hq (and can be received by others in the troop if they join the group too).

Close this if that solves the need well enough for now :)

**Comment by amcjen** [comment]
Closing, as it's handled by mesh.announce instead!
