### ISSUE TITLE
git problem with update in mac osx (10.6.8)

### ISSUE THREAD

**Issue by pbarooah** [Pinoccio/firmware-pinoccio#9]
hi,
## I'm running snow leopard, here's the problem I'm running into:

Prabirs-MacBook-Air:~ pbarooah$ git clone https://github.com/Pinoccio/firmware-pinoccio.git
dyld: lazy symbol binding failed: Symbol not found: ___strlcpy_chk
  Referenced from: /usr/bin/git
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___strlcpy_chk
  Referenced from: /usr/bin/git
  Expected in: /usr/lib/libSystem.B.dylib
## Trace/BPT trap: 5

I then I re-installed(?) git by asking xcode to install command line tools. Then I could run this line, and it created the firmware-pinoccio/ folder. 
But when I tried the next command: "./update.sh", it said: "Git version too old. Found: 1.7.12.4 (Apple Git-37). Required: 1.8.3"
So I installed the latest git, but due to paths pointing to the old installation (I guess), the problem persisted. At that point I did:
"sudo cp /usr/local/git/bin/git /usr/bin"
which updated git:

Prabirs-MacBook-Air:~ pbarooah$ git version
git version 2.0.1

But now when I trued to run update, I get the same errors that I encountered in the very beginning about lazy bindings and what not.

Any help would be greatly appreciated.

**Comment by matthijskooijman** [comment]
Hm, this is very much not a problem of our code but your system. I'd be happy to help nonetheless, except that I don't really know much about OSX. Perhaps @erictj has an idea?

As for running the wrong git, apperently the git installed by Apple lives in /usr/bin, but your custom version lives in /usr/local/bin. Instead of copying the binary (which probably doesn't work because git also has stuff in /usr/(local)/lib/git or wherever), you could check your `$PATH` shell variable, which is used to look up commands (e.g. find `/usr/bin/git` or `/usr/local/bin/git` when you enter `git` as a command). It looks like `/usr/local/bin` is not in your `$PATH`, or it is after `/usr/bin` perhaps.

**Comment by pbarooah** [comment]
Hi,

I appreciate your willingness to help! I am not an systems expert so I didn't know whether the problem is due to git code or my system.

I updated the path to make sure /usr/local/bin appears first in the path, but still the same problem.

echo $PATH
/usr/local/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/local/bin:/opt/local/sbin:/Users/pbarooah/anaconda/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/local/bin:/opt/local/sbin:/Users/pbarooah/anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/usr/texbin:/Library/PostgreSQL/9.1/bin/:/Library/Frameworks/Python.framework/Versions/Current/bin:/Users/pbarooah/anaconda/bin

**Comment by matthijskooijman** [comment]
How did you install the newer version of git?

**Comment by pbarooah** [comment]
from 
https://code.google.com/p/git-osx-installer/

after seeing some comments about troubles with the laterst version, I installed git version 1.8.5.2. After some mucking around with PATH variables, I was able to make the system point to this version of git. (strangely, putting /usr/local/bin ahead of /usr/bin in the path didn't cut it, 'which git' would still return '/usr/bin/git'. I had to remove the git in /usr/bin/ and only then the command 'git' would point to the version in /usr/local/bin/)
But still the same problem!

**Comment by atamariya** [comment]
You can check two things:
- This file exists: /usr/lib/libSystem.B.dylib
- Your LD_LIBRARY_PATH has the path to correct dependent library.

**Comment by Haifisch** [comment]
If you'd like to try running `xcode-select --install` to reinstall the latest Xcode tools, if that doesn't help, I suggest installing "brew" (http://brew.sh/) if you don't already have it installed, and run `brew install git` to install a version of git that may be the newest, brew should also handle any library dependencies.
